/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as NewRouteImport } from './routes/new'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OffersIdRouteImport } from './routes/offers.$id'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIdRoute = OffersIdRouteImport.update({
  id: '/offers/$id',
  path: '/offers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/database': typeof DatabaseRoute
  '/devices': typeof DevicesRoute
  '/new': typeof NewRoute
  '/quick': typeof QuickRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/templates': typeof TemplatesRoute
  '/offers/$id': typeof OffersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/database': typeof DatabaseRoute
  '/devices': typeof DevicesRoute
  '/new': typeof NewRoute
  '/quick': typeof QuickRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/templates': typeof TemplatesRoute
  '/offers/$id': typeof OffersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/contacts': typeof ContactsRoute
  '/database': typeof DatabaseRoute
  '/devices': typeof DevicesRoute
  '/new': typeof NewRoute
  '/quick': typeof QuickRoute
  '/settings': typeof SettingsRoute
  '/sites': typeof SitesRoute
  '/templates': typeof TemplatesRoute
  '/offers/$id': typeof OffersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/contacts'
    | '/database'
    | '/devices'
    | '/new'
    | '/quick'
    | '/settings'
    | '/sites'
    | '/templates'
    | '/offers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/contacts'
    | '/database'
    | '/devices'
    | '/new'
    | '/quick'
    | '/settings'
    | '/sites'
    | '/templates'
    | '/offers/$id'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/contacts'
    | '/database'
    | '/devices'
    | '/new'
    | '/quick'
    | '/settings'
    | '/sites'
    | '/templates'
    | '/offers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  ContactsRoute: typeof ContactsRoute
  DatabaseRoute: typeof DatabaseRoute
  DevicesRoute: typeof DevicesRoute
  NewRoute: typeof NewRoute
  QuickRoute: typeof QuickRoute
  SettingsRoute: typeof SettingsRoute
  SitesRoute: typeof SitesRoute
  TemplatesRoute: typeof TemplatesRoute
  OffersIdRoute: typeof OffersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$id': {
      id: '/offers/$id'
      path: '/offers/$id'
      fullPath: '/offers/$id'
      preLoaderRoute: typeof OffersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  ContactsRoute: ContactsRoute,
  DatabaseRoute: DatabaseRoute,
  DevicesRoute: DevicesRoute,
  NewRoute: NewRoute,
  QuickRoute: QuickRoute,
  SettingsRoute: SettingsRoute,
  SitesRoute: SitesRoute,
  TemplatesRoute: TemplatesRoute,
  OffersIdRoute: OffersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
